on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  pull_request:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.13.1
      - run: opam env >> $GITHUB_ENV
      - run: opam install dune
      - run: opam install ppx_deriving visitors easy_logging zarith yojson core_unix odoc menhir
      - run: make build
      - run: make test
